name: sitemap_add

on:
  schedule:
    - cron:  '30 14 * * *'
  workflow_dispatch:
jobs:
  build:
    name: add
    runs-on: ubuntu-latest
    timeout-minutes: 180 # タイムアウト設定しないと永遠に処理走って大変になる場合がある
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: npm
    - name: Install Dependencies
      run: npm ci
    - name: Create Sitemap
      run: npm run add
    - name: Git Setting
      run: |
        git config --local user.email 136794662+tokokitabutsuri@users.noreply.github.com
        git config --local user.name tokokitabutsuri
    - name: Commit Sitemap
      run: |
        git add sitemap_article.xml
        git commit -m "update sitemap_article.xml by Github Actions"
        git pull
        git push origin